# Generated by Django 4.0.1 on 2022-01-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='created_at',
            new_name='creationDate',
        ),
    ]
