# Generated by Django 4.0.1 on 2022-02-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_rename_created_at_deck_creationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='card',
            name='deck_type',
            field=models.CharField(choices=[('P', 'Perfect'), ('S', 'Self'), ('C', 'Checkbox')], default='S', max_length=1),
        ),
    ]
